name: Build Windows Executable - for branch test (GTK3 for Projector) only !

on:
  push:
    # AGe new only for branch test
    branches: [ test ] # AGe new
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        architecture: [x64, x86]
        # Add Python version 3.7 and 3.9 for being able to test issue #1170 and maybe #1174
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # Import submodule PrintrunGTK3
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        architecture: ${{ matrix.architecture }}
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pyinstaller setuptools wheel simplejson polygon3 cython cffi -r requirements.txt
    - name: Build Cython ext
      run: |
        python setup.py build_ext --inplace
    - name: Make pyinstaller spec
      run: |
        pyi-makespec --hidden-import="pkg_resources.py2_warn" -F --add-binary "PrintrunGTK3/GTK3Windows10-64/*.dll;." --add-data "VERSION;cairocffi" --add-data "VERSION;cairosvg" --add-data "images/*;images" --add-data "*.png;." --add-data "*.ico;." -w -i pronterface.ico pronterface.py
    - name: Make pyinstaller build
      run: |
        pyinstaller --clean pronterface.spec -y
    - name: Upload artifacts for inspection
      uses: actions/upload-artifact@v2
      with:
        name: exe_${{ matrix.os }}_${{ matrix.architecture }}_${{ matrix.python-version }}
        path: dist/pronterface.exe
